# f=open("text.txt","wb")
# f.write("hello\nworld".encode("utf-8"))
# f.close()

# f=open("text.txt","w")
# f.write("hello\nworld")
# f.close()
#
# f=open("text1.txt","w")
# f.write("hello\r\nworld")
# f.close()
f=open("新建文本文档.txt","rb")
va=f.read()
print(va)
f.close()
f=open("新建文本文档.txt","r")
va=f.read()
print(">>"+va)
f.close()