from gun import *
laowang=Person("老王")
AK47=Gun("AK47")
danjia=DanJia(30)
bullet=Bullet(20)
laosong = Person("敌人")
laowang.input_bullet(danjia,bullet,5)
laowang.input_danjia(AK47,danjia)
laowang.take_gun(AK47)
print(danjia)
print(laowang)
print(laosong)

laowang.shot(laosong)
print(laosong)
laowang.shot(laosong)
print(laosong)
laowang.shot(laosong)
print(laosong)
laowang.shot(laosong)
print(laosong)
laowang.shot(laosong)
print(laosong)
laowang.shot(laosong)